[package]
authors = ["Daniel Egger <daniel@eggers-club.de>"]
categories = [
    "embedded",
    "no-std",
    "bsp",
]
keywords = [
    "arm",
    "cortex-m",
    "template",
]
name = "nucleo-f042k6"
version = "0.1.1"

[dependencies]
bare-metal = "0.1.2"
cortex-m = "0.4.3"
nb = "0.1.1"
numtoa = "0.0.7"
static-ref = "0.2.1"
vcell = "0.1.0"
volatile-register = "0.2.0"
panic-abort = "0.1.1"
ssd1306 = "0.1.0"

[dependencies.cortex-m-rt]
version = "0.4.0"

[dependencies.embedded-hal]
features = ["unproven"]
version = "0.1.2"

[dependencies.stm32f042]
features = ["rt"]
version = "0.5.3"

[dependencies.stm32f042-hal]
features = ["rt"]
version = "0.3.7"

[features]
default = ["rt"]
rt = []
[profile.dev]
debug = true
lto = true

[profile.release]
debug = true
lto = true
opt-level = "s"
